version: '3.9'
services:
  app:
    build: ./app
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      INTERVAL: ${INTERVAL}
      API_URL: ${API_URL}
      ADMIN_SECRET: ${ADMIN_SECRET}
    devices:
      - '${HOST_PORT}:/dev/ttyUSB0'
